#
# gp-firebase-devenv
# Copyright (c) 2023, Greg PFISTER. MIT License.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

FROM ghcr.io/gpfister/gp-base-devenv:20.04-1.0.0

LABEL org.opencontainers.image.source=https://github.com/gpfister/gp-docker-devenv
LABEL org.opencontainers.image.description "Docker dev image using ghcr.io/gpfister/gp-base-devenv:20.04-1.0.0"
LABEL org.opencontainers.image.licenses=MIT

USER root

# Command script
RUN mkdir -p /opt/docker
COPY dist/run.sh /opt/docker/

# Update all
RUN apt-get update && \
    apt-get full-upgrade -y && \
    apt-get autoremove -y && \ 
    apt-get autoclean

# Remove any previous install
RUN dpkg --remove docker docker-engine docker.io containerd runc

# Install Docker
RUN apt-get update && \
    apt-get install -y ca-certificates \
                       curl \
                       gnupg \
                       lsb-release && \
    mkdir -m 0755 -p /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    apt-get update && \
    apt-get install -y docker-ce \
                       docker-ce-cli \
                       containerd.io  \
                       docker-buildx-plugin  \
                       docker-compose-plugin && \
    apt-get autoclean -y && \
    apt-get autoremove -y

# Set authorizations
RUN usermod -aG docker vscode

# Switch back to user
USER vscode
WORKDIR /home/vscode

ENTRYPOINT ["sudo", "/opt/docker/run.sh"]
